### ISSUE TITLE
Error running docker / docker compose

### ISSUE THREAD

**Issue by maaknaamaan** [hackthedev/dcts-shipping#12]
Trying to run this on a docker, but it throws this error;

sudo docker run --name dcts-server  -p 8080:2052 ghcr.io/t2vee/dcts;

Error response from daemon: Head "https://ghcr.io/v2/t2vee/dcts/manifests/latest": unauthorized

Running it with the docker compose file throw the same error.

**Comment by hackthedev** [comment]
Hi i would need to further check it out as it has been made by @t2vee . It looks like the link is dead but like i said gotta check it out

**Comment by t2vee** [comment]
Apologies, I had forgot to set the visibility on the package to public.
Been switched over and correctly able to pull

**Comment by t2vee** [comment]
@hackthedev I see you deleted the associated docker files on the main branch, after confirming that docker is running as it should did you want me to open another pull request or would you prefer to roll back commits?

**Comment by hackthedev** [comment]
@t2vee i removed it as i tried to setup a workflow but failed. it seemed like the url in the file for the docker image i believe was private as others didnt have access to it and showed us a "UNAUTHORISED" error message.

Feel free to make another pull request if it works. sorry for the inconvenience

**Comment by Bunny-B** [comment]
$ curl -L -O https://github.com/t2vee/dcts-shipping/raw/docker-support/docker/docker-compose.yml
https://github.com/t2vee/dcts-shipping/raw/docker-support/docker/docker-compose.yml dont seem to exist 

also for windows it should be 
curl.exe -L -O "https://github.com/t2vee/dcts-shipping/raw/docker-support/docker/docker-compose.yml"

**Comment by hackthedev** [comment]
> $ curl -L -O https://github.com/t2vee/dcts-shipping/raw/docker-support/docker/docker-compose.yml https://github.com/t2vee/dcts-shipping/raw/docker-support/docker/docker-compose.yml dont seem to exist
> 
> also for windows it should be curl.exe -L -O "https://github.com/t2vee/dcts-shipping/raw/docker-support/docker/docker-compose.yml"

I can use curl without the .exe on windows just fine. depends how you install it

**Comment by hackthedev** [comment]
@t2vee  apparently there is a issue [see here](https://github.com/hackthedev/dcts-shipping/actions/runs/9700321117/job/26771433371). Do you know how we could fix it?

**Comment by t2vee** [comment]
can you confirm that `Allow all actions and reusable workflows `  is selected under Actions Permissions and that `Read and write permissions` are set under Workflow permissions in Settings > Actions > General?

Then try triggering the action again with a commit and should be good 👍

**Comment by hackthedev** [comment]
> can you confirm that `Allow all actions and reusable workflows ` is selected under Actions Permissions and that `Read and write permissions` are set under Workflow permissions in Settings > Actions > General?
> 
> Then try triggering the action again with a commit and should be good 👍

it seems to work now. the write permission wasnt set
