### ISSUE TITLE
Docker volumes

### ISSUE THREAD

**Issue by ExXxtr3me** [hackthedev/dcts-shipping#22]
Could you please tell me which volumes i have to map on my server if i don't want to start from zero after every update?

**Comment by hackthedev** [comment]
@t2vee do you know how this could be fixed? my experience with docker is pretty limited

**Comment by t2vee** [comment]
You can use these volume maps for crucial data:
**Config:**
- `./config.json:/app/config.json`
- `./config_backups:/app/config_backups`

**Chat Data:**
- `./chats:/app/chats`
- `./uploads:/app/public/uploads`

**Logs:**
- `./logs:/app/logs`


Also @hackthedev, could you move this issue to a discussion? It would be more suitable so other users can also ask docker-related questions
