### ISSUE TITLE
Does DCTS imply I'm directly connecting to my chat buddies through sockets?

### ISSUE THREAD

**Issue by Leopere** [hackthedev/dcts-shipping#30]
Theres a lot of privacy concerns I would have if true.

**Comment by Leopere** [comment]
If this is how this is architected can we have a mode where it's optionally available that a user can communicate directly connected through sockets to the server only?

**Comment by t2vee** [comment]
No. DCTS uses a server/backend api as a middleman between all communication, no communication is done from peer to peer.
`Direct Communication Through Sockets`, sockets meaning websockets the technology that dcts primarily uses, if you have privacy concerns about data security, when running through https all traffic is sent over WSS (Secure Websockets) which intern uses the same TLS encryption that https uses.

**Comment by hackthedev** [comment]
![DCTS Connection Diagram](https://github.com/user-attachments/assets/002705cf-3d19-49be-b8e6-0e3f217dc387)
*Receive
